remote_theme: daattali/beautiful-jekyll

title: <img src="/assets/img/logo_transparent.png" />

author: BioAnalytics Consulting

navbar-links:
  Blog: "https://deanattali.com/"
  Open-Source: "https://deanattali.com/projects"
  Schedule meeting: "https://calendly.com/attalitech/meeting"
  Contact: "/contact"
  ❤ Support: "https://github.com/sponsors/daattali"

site-css: "/assets/css/attalitech.css"


keywords: "r shiny,shiny developer,shiny consultant,r consultant,shiny apps"

mobile-theme-col: "#0085A1"
navbar-col: "#cde0fd"
navbar-text-col: "#184377"
navbar-border-col: "#90afd4"

social-network-links:
  email: "dean@attalitech.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  stackoverflow: "3943160/daattali"
  calendly: "attalitech/meeting"
  youtube: "channel/UCR3No6pYhA1S7FZ0PbLKlgQ"

url-pretty: "BioAnalyticsConsulting.com.au"

footer-img: "/assets/img/footer-bg.png"

google_analytics: "UA-59820529-1"

timezone: "Australia/Melbourne"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "AttaliTech provides world-class R/Shiny consulting. Services include building professional Shiny apps, auditing Shiny code, package building, mentoring and training. Led by renowned expert Dean Attali."
      share-img: "/assets/img/attalitech.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
